FROM node:20 AS base

WORKDIR /client

COPY package*.json ./

RUN rm -rf node_modules && npm cache clean --force && npm install

# Copy the rest of the app's source code and build it
COPY . .
RUN npm run build

# Start nginx
CMD ["npm", "run", "client"]